In [1]:
import pandas as pd

In [2]:
reviews = pd.read_csv("Reviews.csv")

In [4]:
reviews.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...  
3         Cough Medicine  If you are looking for the secret ingredient i...  
4            Great taffy  Great taffy at a great price.  There was a wid...

In [5]:
import numpy as np

In [10]:
reviews['Score'].value_counts()

5    363111
4     80655
1     52264
3     42638
2     29743
Name: Score, dtype: int64

In [11]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

sid = SentimentIntensityAnalyzer()

In [12]:
reviews['scores'] = reviews['Text'].apply(lambda Text: sid.polarity_scores(Text))

reviews['compound']  = reviews['scores'].apply(lambda score_dict: score_dict['compound'])

reviews.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  \
0  Good Quality Dog Food  I have bought several of the Vitality canned d...   
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...   
2  "Delight" says it all  This is a confection that has been around a fe...   
3         Cough Medicine  If you are looking for the secret ingredient i...   
4            Great taffy  Great taffy at a great price.  There was a wid...   

                                              scores  compound  
0  {'neg': 0.0, 'neu': 0.695, 'pos': 0.305, 'comp...    0.9441  
1  {'neg': 0.138, 'neu': 0.862, 'pos': 0.0, 'comp...   -0.5664  
2  {'neg': 0.091, 'neu': 0.754, 'pos': 0.155, 'co...    0.8265  
3  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...    0.0000  
4  {'neg': 0.0, 'neu': 0.552, 'pos': 0.448, 'comp...    0.9468

In [13]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [23]:
reviews['comp_score'] = reviews['compound'].apply(lambda c: 1 if(c >=-1 and c < -0.6) else (2 if(c >= -0.6 and c < -0.2) else(3 if(c >= -0.2 and c < 0.2) else (4 if(c >= 0.2 and c < 0.6) else 5 ))))

In [16]:
type(reviews['Score'][0])

numpy.int64

In [24]:
reviews.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  \
0  Good Quality Dog Food  I have bought several of the Vitality canned d...   
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...   
2  "Delight" says it all  This is a confection that has been around a fe...   
3         Cough Medicine  If you are looking for the secret ingredient i...   
4            Great taffy  Great taffy at a great price.  There was a wid...   

                                              scores  compound  comp_score  
0  {'neg': 0.0, 'neu': 0.695, 'pos': 0.305, 'comp...    0.9441           5  
1  {'neg': 0.138, 'neu': 0.862, 'pos': 0.0, 'comp...   -0.5664           2  
2  {'neg': 0.091, 'neu': 0.754, 'pos': 0.155, 'co...    0.8265           5  
3  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...    0.0000           3  
4  {'neg': 0.0, 'neu': 0.552, 'pos': 0.448, 'comp...    0.9468           5

In [26]:
accuracy_score(reviews['Score'],reviews['comp_score'])

0.5936391097286998

In [27]:
print(classification_report(reviews['Score'],reviews['comp_score']))

              precision    recall  f1-score   support

           1       0.52      0.24      0.33     52264
           2       0.15      0.14      0.14     29743
           3       0.14      0.10      0.12     42638
           4       0.15      0.12      0.14     80655
           5       0.73      0.84      0.78    363111

    accuracy                           0.59    568411
   macro avg       0.34      0.29      0.30    568411
weighted avg       0.55      0.59      0.57    568411



In [29]:
print(confusion_matrix(reviews['Score'],reviews['comp_score']))

[[ 12452   9010   7108   9114  14580]
 [  3832   4058   3981   5382  12490]
 [  2374   3890   4447   7500  24427]
 [  1516   2750   4046   9984  62359]
 [  3983   7039  11752  33847 306490]]
